In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x.__class__

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [6]:
W = np.array([[1,2,3],[4,5,6]])
W.shape

(2, 3)

In [7]:
W.ndim

2

### 1.1.2 행렬의 원소별 연산

In [8]:
W=np.array([[1,2,3],[4,5,6]])
X=np.array([[0,1,2],[3,4,5]])
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [9]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

### 1.1.3. 브로드캐스트

In [10]:
A = np.array([[1,2],[3,4]])
A*10

array([[10, 20],
       [30, 40]])

In [11]:
b = np.array([10,20])
A*b

array([[10, 40],
       [30, 80]])

### 1.1.4. 벡터의 내적과 행렬의 곱

In [12]:
# 벡터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [13]:
# 행렬의 곱
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [14]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [19]:
W1= np.random.randn(2,4)
b1= np.random.randn(4)
x=  np.random.randn(10,2)
h=np.matmul(x,W1)+b1
h

array([[-0.54488552, -2.11097247, -1.15754358,  0.7325776 ],
       [ 0.44414573,  0.38651467, -1.6479366 , -0.21726729],
       [-0.07245139, -0.31320743, -1.68124975,  0.05299818],
       [-1.03722035, -3.67423745, -0.76025753,  1.32492446],
       [-0.119819  ,  0.52961725, -2.11840151, -0.26094564],
       [-0.75232175, -2.71377579, -1.01688497,  0.96129427],
       [ 0.42518366,  0.7173227 , -1.81978227, -0.34048358],
       [-0.19800201, -0.05252114, -1.89550646, -0.04218461],
       [ 0.45588125,  2.76710186, -2.77896039, -1.10653222],
       [ 0.88830422, -0.98968628, -0.67268394,  0.28900241]])

In [20]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
a = sigmoid(h)
a

array([[0.36705182, 0.10803492, 0.23911392, 0.67537065],
       [0.60924643, 0.5954434 , 0.16138802, 0.44589584],
       [0.48189507, 0.42233204, 0.15693005, 0.51324645],
       [0.26168668, 0.02474109, 0.31859036, 0.78999984],
       [0.47008104, 0.62939384, 0.10732112, 0.43513126],
       [0.32031561, 0.06216536, 0.26563461, 0.72338087],
       [0.60472299, 0.67201718, 0.13946   , 0.41569201],
       [0.45066059, 0.48687273, 0.1306179 , 0.48945541],
       [0.61203664, 0.94087196, 0.05847176, 0.24851796],
       [0.7085401 , 0.27097405, 0.33789612, 0.57175189]])

In [21]:
import numpy as np 
def sigmoid(x):
    return 1/(1+np.exp(-x))

x=  np.random.randn(10,2)
W1= np.random.randn(2,4)
b1= np.random.randn(4)
W2= np.random.randn(4,3)
b2= np.random.randn(3)
h=np.matmul(x,W1)+b1
a=sigmoid(h)
s=np.matmul(a,W2)+b2
s


array([[-2.05486387,  0.59281129,  0.68141777],
       [-2.07479077,  0.72049925,  1.33907583],
       [-2.03748916,  0.64961257,  1.10940813],
       [-2.2708154 ,  0.99275406,  1.58021751],
       [-2.54599444,  1.32405246,  1.44839703],
       [-2.0993083 ,  0.83221027,  1.79036356],
       [-2.29880339,  0.92965241,  0.84085099],
       [-2.4973039 ,  1.22300541,  1.06411256],
       [-2.13480672,  0.7790694 ,  1.22152484],
       [-2.51226236,  1.2671649 ,  1.29817486]])

In [1]:
import numpy as np 
D,N = 8,7
x = np.random.randn(1,D)
y = np.repeat(x,N,axis=0)
dy = np.random.randn(N,D)
dx = np.sum(dy,axis=0, keepdims=True)

In [2]:
x

array([[ 2.50014386,  0.02123954, -1.12133422,  1.93632597, -2.20962429,
         1.10626269,  0.90813583, -0.41375417]])

In [8]:
y

array([[ 2.50014386,  0.02123954, -1.12133422,  1.93632597, -2.20962429,
         1.10626269,  0.90813583, -0.41375417],
       [ 2.50014386,  0.02123954, -1.12133422,  1.93632597, -2.20962429,
         1.10626269,  0.90813583, -0.41375417],
       [ 2.50014386,  0.02123954, -1.12133422,  1.93632597, -2.20962429,
         1.10626269,  0.90813583, -0.41375417],
       [ 2.50014386,  0.02123954, -1.12133422,  1.93632597, -2.20962429,
         1.10626269,  0.90813583, -0.41375417],
       [ 2.50014386,  0.02123954, -1.12133422,  1.93632597, -2.20962429,
         1.10626269,  0.90813583, -0.41375417],
       [ 2.50014386,  0.02123954, -1.12133422,  1.93632597, -2.20962429,
         1.10626269,  0.90813583, -0.41375417],
       [ 2.50014386,  0.02123954, -1.12133422,  1.93632597, -2.20962429,
         1.10626269,  0.90813583, -0.41375417]])

In [6]:
dy.shape

(7, 8)

In [9]:
dx.shape

(1, 8)

In [11]:
import numpy as np 
D,N = 8,7
x = np.random.randn(N,D)
y = np.sum(x,axis=0, keepdims=True)

dy = np.random.randn(1,D)
y = np.repeat(dy,N,axis=0)

In [12]:
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.dot(x, W)
        self.x = x
        return out

    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx

In [1]:

class Sigmoid:
    def __init__(self):
        self.params, self.grads = [], []
        self.out = None

    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx

In [2]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        self.x = x
        return out

    def backward(self, dout):
        W, b = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        db = np.sum(dout, axis=0)

        self.grads[0][...] = dW
        self.grads[1][...] = db
        return dx


In [3]:
class SGD:
    '''
    확률적 경사하강법(Stochastic Gradient Descent)
    '''
    def __init__(self, lr=0.01):
        self.lr = lr
        
    def update(self, params, grads):
        for i in range(len(params)):
            params[i] -= self.lr * grads[i]
